# Adding parameters for model, to have it 
# all in one-place!


# using DiT 2nd smallest
# with patch-size2, is close...
dit_params:
  patch_height: 2
  patch_width: 2
  num_heads: 12
  layers: 12
  h_dim: 768

  # latent-space
  # sdxl for now...
  im_height: 32
  im_width: 32
  im_channels: 4

  # matching hidden-dim
  timestep_dim: 768

# for VAE...
VAE_params:
  im_height: 256
  im_width: 256
  im_channels: 3

  latent_height: 32
  latent_width: 32
  latent_channels: 4
